apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: stability97
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  generation: 1
  labels:
    app: stabi-cpu-memory
  name: stabi-cpu-memory
  namespace: stability97
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: stabi-cpu-memory
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: stabi-cpu-memory
    spec:
      containers:
      - name: stabi-cpu-memory
        # - -c 8 --vm 1 --vm-bytes 13143.93M --vm-method prime-gray-0 --mmaphuge 1 --vm-keep -v
        image: quay.io/midu/stress-ng:03676022
        command:
        - stress-ng
        args:
        - "--cpu"
        - "8"
        - "--vm"
        - "1"
        - "--vm-bytes"
        - "13143.93M"
        - "--vm-method"
        - "prime-gray-0"
        - "--mmaphuge"
        - "1"
        - "--vm-keep"
        - "--metrics-brief"
        imagePullPolicy: IfNotPresent
        name: stabi-cpu-memory
        resources:
          limits:
            cpu: 3510m
            memory: 15772.716M
          requests:
            cpu: 3510m
            memory: 15772.716M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
